apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config2
immutable: false
data:
  username: admin
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
        replSetName: "rs0"
